# Generated by Django 2.2.6 on 2019-11-04 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='sexo',
            field=models.CharField(choices=[('---', '---'), ('M', 'Masculino'), ('F', 'Feminino'), ('ND', 'Não Definido')], max_length=255),
        ),
    ]
