# Generated by Django 2.2.6 on 2019-11-04 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0002_auto_20191104_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='idade',
            field=models.CharField(max_length=255),
        ),
    ]
