# Generated by Django 2.2.6 on 2019-11-12 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0003_auto_20191104_2056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='bairro',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='dataNascimento',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='periodo',
        ),
        migrations.AlterField(
            model_name='curso',
            name='cpf',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='curso',
            name='rg',
            field=models.CharField(max_length=255),
        ),
    ]
