# Generated by Django 2.2.6 on 2019-11-12 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0004_auto_20191112_1858'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='numero_de_recidencia',
        ),
    ]
