# Generated by Django 2.2.6 on 2019-11-13 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entretenimentos', '0003_remove_entretenimento_numero_de_recidencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='entretenimento',
            name='periodo',
            field=models.CharField(choices=[('---', '---'), ('M', 'Manhã'), ('T', 'Tarde'), ('N', 'noite')], default=1, max_length=255),
            preserve_default=False,
        ),
    ]
